### PR TITLE
Improve.docs

### PR DESCRIPTION
**Pull request by sinarueeger**
- OSX binary 0.5.2
- Added to all the `1KG/EUR` that any POP or SUPERPOP can be used. 
- Changed Version number in README file from 0.5.1 > 0.5.2

### CODE REVIEW

**Comment by aaronmcdaid** [comment]
There seems to be a problem in the docs where `á`, and some umlauts, are replaced with `??`. Some maybe this shouldn't be merged as-is

**Comment by sinarueeger** [comment]
I fix that, give me a sec

**Comment by aaronmcdaid** [comment]
:+1:

**Comment by aaronmcdaid** [comment]
I've just merged this a few seconds ago, and I hope to send a PR with the new binary this evening

For 0.5.2 (I had said 1.5.2 earlier, my mistake!)

**Pull request merged**
