### PR TITLE
Docs.and.stu

### PR DESCRIPTION
**Pull request by aaronmcdaid**
A few small things, as a follow up to PR #76 

 - another small `docu` -> `doc` change
 - remove two unnecessary files
 - Improve the `make` process. It now (re)builds `stu/stu` every time. This wastes two or three seconds, but it's more reliable because this needs to work on both Linux and on Mac and therefore we can't include a single binary for both.

### CODE REVIEW

**Comment by aaronmcdaid** [comment]
PS: I've only just realised/remembered that this already accepts `1KG/AFR` and `1KG/GBR` and so on, basically any `pop` or `super_pop` in the panel file. I forgot that I had done that already. Maybe you had already worked that out, @sinarueeger !?

**Comment by aaronmcdaid** [comment]
No need to recompile the binaries; neither this PR (#77) nor the last one (#76) include changes requiring a recompilation. As long as you recompiled the Mac binary after #75 was merged, then we're good. I think you already added a new Mac binary


In general, @sinarueeger , we need to update the binary if we update the code or if we update `doc/usage.txt` (because the latter is included in the binary). If we make a change to the code, we should update the version number and the date in the first line of `doc/usage.txt`. Ideally, this change would happen in the same commit; alternatively, the update to `doc/usage.txt` should be in a later commit in order to ensure that the date in `doc/usage.txt` (and therefore in the binary) is a *conservative* estimate of the state of the binary. With this scheme, we can easily check with users which version of the binary they have.

Also `git grep` is a cool piece of functionality that is built into `git`. In order to check which version of the usage text is built into the compiled binaries, I ran `git grep 2018-10-29` and got this output:

````
$ git grep ssimp-0.5.1
VERSION:ssimp-0.5.1     (2018-10-29)
Binary file compiled/ssimp-linux-0.5.1 matches
Binary file compiled/ssimp-osx-0.5.1 matches
doc/usage.txt:[ssimp-0.5.1     (2018-10-29)]

$ git grep 2018-10-29
VERSION:ssimp-0.5.1     (2018-10-29)
Binary file compiled/ssimp-linux-0.5.1 matches
Binary file compiled/ssimp-osx-0.5.1 matches
doc/usage.txt:[ssimp-0.5.1     (2018-10-29)]
````

`git grep` searches for the string in all the files that are in the git repository. By default, however, it looks only in the current working directory and its subfolders; I sometimes forget this and get strange results. This allows me to check which version the Mac binary is, despite the fact that I cannot run the Mac binary on my Linux laptop

**Comment by sinarueeger** [comment]
I see - thank you @aaronmcdaid for the explanation. 

But I did make changes to `doc/usage.txt` and I also changed `docs/` to `doc/` at a few places in issue #76 . 

Just want to be sure that we don't need to recompile ;-)

**Comment by aaronmcdaid** [comment]
Doh! We do need to recompile then! I'll make a PR in a few minutes about this

**Comment by aaronmcdaid** [comment]
... as proof that a recompilation is needed, `git grep` to the rescue again:

````
$ git grep https://github.com/zkutalik/ssimp_software/blob/master/doc/examples.md
Binary file compiled/ssimp-osx-0.5.1 matches
doc/usage.txt:For examples, visit https://github.com/zkutalik/ssimp_software/blob/master/doc/examples.md

e$ git grep https://github.com/sinarueeger/ssimp_software/blob/master/docu/examples.md
Binary file compiled/ssimp-linux-0.5.1 matches

````

This shows that the old url is still in the linux binary, while the mac binary has the new url

**Pull request merged**
